[package]
name = "mw-native"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
ab_glyph.workspace = true
anyhow.workspace = true
base64.workspace = true
bytemuck.workspace = true
env_logger.workspace = true
futures-lite.workspace = true
image.workspace = true
log.workspace = true
mw-checkpoint = { package = "mw-tools", path = "../mw-tools" }
mw-core = { path = "../mw-core" }
serde_json.workspace = true
wgpu.workspace = true
winit.workspace = true
ureq.workspace = true
